services:
  web:
    build: .
    image: rest-apis-flask-python
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: